### ISSUE TITLE
[Feature Request] Customizable  Tooltip

### ISSUE THREAD

**Issue by c3p0vsr2d2** [mentalilll/ha-vpd-chart#13]
**Checklist**
- [X ] I am running the latest version of the card
- [X ] I checked if there isn't another feature request opened with the same request
- [ X] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
With a lot of sensors, the chart becomes very crowded with the tooltips being displayer

**Describe the solution you'd like**
Have an option to disable the tooltip shown on the chart all the time

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mentalilll** [comment]
Would it help to show only name, and show the other information after hover?

**Comment by c3p0vsr2d2** [comment]
thanks @mentalilll - appreciate the quick response.
Yes, showing only name (and more details on hover) would also be good enough for now as well (if there is an existing way to configure this, please let me know).

However, I suspect that with a lot of sensors with similar temp and humidity, the chart will still be crowded, and there will be overlaps between the name-only tooltips. As a longer term solution, zooming in to the chart might also be useful - or there may be better solutions.

regardless, thanks for ha-vpd-chart!

**Comment by mentalilll** [comment]
![image](https://github.com/user-attachments/assets/95f79a79-98db-43e2-80a0-f338842f8d85)

Zoom like this? Already Possible :P. enable_zoom: true

but i also implement the hover tooltip, =)

**Comment by c3p0vsr2d2** [comment]
Thanks for pointing me to the zoom option, and TIA for the tooltip changes !

One more feature request - can the font size be maintained with zoom? :P

**Comment by mentalilll** [comment]
done with new release :)

**Comment by c3p0vsr2d2** [comment]
@mentalilll many thanks for considering these features, and the associated code updates.

However, I tried the 1.4.9 release, but I am not able to see the two features discussed in this thread:
1. Showing only the name on the chart till hover
2. Zooming into chart without zooming the tooltip text

Could you please let me know if there are specific options to get the above two to work?

**Comment by mentalilll** [comment]
Hey,
for 

1. enable_show_always_informations to false
2. zooming is currently bound to text size, so if you scroll in, text gets smaller

do you need an option to disable 2?

**Comment by c3p0vsr2d2** [comment]
@mentalilll this is unfortunately not working for me - I do not see `enable_show_always_informations: false` being recognized. Setting it to true does not change anything. Zoom text gets bigger when I zoom in as well.

I am on 1.4.9, and checked this after redownloading it, and also after reinstalling it. If there is anything else I should be doing, please let me know.

**Comment by mentalilll** [comment]
It should work now like intended

**Comment by c3p0vsr2d2** [comment]
@mentalilll I am on 1.50, and I removed the integration and reinstalled it. But I still see the following:

![image](https://github.com/user-attachments/assets/62646ca0-e820-459c-b613-0bd7aae932d4)

1. The text on the tooltip is the same with or without hover (all text, not just name)
2. Text becomes larger on zooming in

Possible that something is wrong on my configuration?

**Comment by mentalilll** [comment]
Could you tell me what Browser you used for this?
I tested on multiple browsers, and devices, and on zoom the text gets smaller scaled for me.
I currently check some Bugs maybe you have some more Information for me :P.
